// NgMakeMySkills/src/app/Components/Common/nav.component.ts
import { Component, OnInit, TemplateRef } from '@angular/core';
import { ModalService } from 'src/app/Services/modal.service';

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css']
})
export class NavComponent implements OnInit {

  constructor(private modalService: ModalService) { }

  ngOnInit() {
  }

  openAccountModal(template: TemplateRef<any>) {
    this.modalService.showModal(template);
  }

}

<nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">#MakeMySkills</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="/create-test" *ngIf="isLoggedIn && isExaminer" class="nav-link">Create Test</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Subjects
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#" *ngFor="let item of topics">{{item.topicName}}</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/all-tests">More Tests</a>
                </li>
                <li class="nav-item dropdown" *ngIf="isLoggedIn">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        My Profile
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="/user-home">Home</a>
                        <a class="dropdown-item" href="#" (click)="openChangePasswordModal($event)">Change Password</a>
                        <a class="dropdown-item" href="#" (click)="logout()">Logout</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" *ngIf="!isLoggedIn" (click)="openAccountModal(e)">Login/Resister</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

// react-makemyskills/src/Components/Common/Nav.js
import React from 'react';
import './Common.css';

function Nav() {

    return (
        <React.Fragment>
            <nav className="navbar navbar-expand-lg navbar-light fixed-top">
                <div className="container">
                    <a className="navbar-brand" href="/">#MakeMySkills</a>

                    <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>

                    <div className="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul className="navbar-nav mr-auto"></ul>
                        <ul className="navbar-nav">
                            <li className="nav-item">
                                <a className="nav-link" href="/create-test">Create Test</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="/tests">Tests</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="##">Subjects </a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="##">Login/Register </a>
                            </li>
                            <li className="nav-item dropdown">
                                <a className="nav-link dropdown-toggle" href="##" id="navbardrop" data-toggle="dropdown">
                                    My Profile
                                </a>
                                <div className="dropdown-menu">
                                    <a className="dropdown-item" href="/user-home">Home</a>
                                    <a className="dropdown-item" href="##">Change Password</a>
                                    <a className="dropdown-item" href="##">Logout</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </React.Fragment>
    )
}

export default Nav
